language: python
puthon: 3.8
branches:
  only:
  - master
  - dev
script:
  echo Starting work...
import:
- source: .travis/default.yml
  if: branch = dev
- source: .travis/release.yml
  if: branch = master
